AllCops:
  RunRailsCops: true
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Rakefile'

Documentation:
  Enabled: false
