# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 753db57dfbe43687426f56336fc1ee10757ae097cd586f2fd34b9eba604dc39de3ee37e8b14fa8e0a082d6311922745f1acb94703ffdb09953eea58329ba57f2

test:
  secret_key_base: 27289eb9c42a0ecfec0056a4069c15d124ac2d2837dacfac7986a2ee64528d59d5d2603c5a41d2cfd10081fe25958b1fdadb4ee4e0b96de185bb13709dd36da5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
